### PR TITLE
RINF translates to rap-inf

### PR DESCRIPTION
**Pull request by paulineleon**
In this [RINFANR5L15B1241](https://git.en-root.org/tricoteuses/data/assemblee-nettoye/Dossiers_Legislatifs_XV_nettoye/blob/ec160f7d701a6ec27286d84498ed75ebd2f6517f/documents/RINF/AN/R5/15/B/001/RINFANR5L15B1241.json#L3) RINF translates into [rap-inf](http://www.assemblee-nationale.fr/15/rap-info/i1241.asp) with prefix **i**.

### CODE REVIEW

**Comment by RouxRC** [comment]
I'm not sure since I haven't looked at this closely in a while, but shouldn't this be a complementary piece instead of a replacement?
i.e shouldn't we keep RINF the way it was and add another entry RAP-INF with the pattern you proposed?

**Comment by paulineleon** [comment]
I forgot the reference about the [structure of the uid](http://www.assemblee-nationale.fr/opendata/Implementation_Referentiel/Identifiants_Referentiels.html#texte-an) which defines RINF but not RAP-INF.

I think a replacement is the right thing to do because all [documents](https://git.en-root.org/tricoteuses/data/assemblee-nettoye/Dossiers_Legislatifs_XV_nettoye/blob/ec160f7d701a6ec27286d84498ed75ebd2f6517f/documents/) with code RINF translate into a URL such as **http://www.assemblee-nationale.fr/15/rap-info/iNNNN.asp** but none of them translate into a URL such as **http://www.assemblee-nationale.fr/15/rapports/rNNNN.asp**

**Comment by RouxRC** [comment]
That makes sense. @mdamien I believe you're the one who introduced it, do you remember whether it was a simple guess or corresponding to a real case?

**Comment by mdamien** [comment]
thanks @paulineleon I believe I added it without properly testing it, simply a copy-paste of the `RAPP` case

**Comment by RouxRC** [comment]
in which case we should totally merge, will do right away then ! thx to you both :)

**Comment by mdamien** [comment]
I also released a new version on PyPI just in case :)

**Pull request merged**
